# Generated by Django 4.2.7 on 2026-05-03 01:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0006_signosvitales_imc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signosvitales',
            name='presion_arterial',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(regex='\\b(7[0-9]|[89][0-9]|1[0-9]{2}|200)\\/(5[0-9]|[6-9][0-9]|1[01][0-9]|120)\\b')], verbose_name='Presión arterial'),
        ),
    ]
