# services/intents.py

INTENTS = {
    "saludo": [
        "hola", "holaa", "hey", "buenas", "que tal", "que onda", "onda", "buen dia", 
        "buenos dias", "buenas tardes", "buenas noches", "holi", "hola lincy", "hola bot",
        "hola lincybot", "saludos", "que hay", "habra alguien por aqui", "hola mundo",
        "necesito ayuda", "puedes ayudarme", "ayuda por favor", "tengo una duda",
        "quisiera hacer una consulta", "me puedes apoyar", "estoy buscando informacion",
        "ocupo ayuda con el sistema", "una pregunta", "tengo un problema", "asistencia",
        "hola salud lince", "bienvenido", "despierta lincybot", "iniciar conversacion",
        "quiero usar el chatbot", "atencion al cliente", "soporte tecnico", "soporte salud lince",
        "hola lince", "que puedes hacer", "en que me puedes ayudar", "ayudame con el sistema",
        "hola quisiera saber algo", "buenos dias tengo una duda", "hola busco orientacion",
        "hey lincy tengo un problema", "buen dia me podrias asesorar", "hola necesito asistencia",
        "saludos salud lince necesito ayuda", "hola quisiera consultar mis datos",
        "que tal lincy me ayudas con una duda", "hola ocupo ver algo de mi cuenta"
    ],
    
    "confirmacion": [
        "si por favor", "asi es", "claro que si", "adelante",
        "me parece bien", "estoy de acuerdo", "perfecto"
    ],

    "recuperar_password": [
        "olvidé mi contraseña", "perdí mi contraseña", "no sé mi contraseña", 
        "no recuerdo mi contraseña", "quiero recuperar mi contraseña", 
        "restablecer contraseña", "resetear mi contraseña", "cambio de contraseña por olvido",
        "necesito mi contraseña de nuevo", "ayuda con mi contraseña",
        "no puedo entrar", "no puedo iniciar sesión", "me deniega el acceso",
        "no me deja ingresar", "usuario bloqueado", "mi cuenta está bloqueada",
        "no reconoce mi entrada", "problemas para loguearme", "no puedo acceder al sistema",
        "error de credenciales", "no entra mi cuenta", "el sistema no me deja pasar",
        "olvidé mi contraseña institucional", "no tengo mi contraseña de salud lince",
        "perdí el acceso a salud lince", "ayuda para entrar a mi expediente",
        "no puedo ver mis datos porque no tengo contraseña", "mi contraseña no funciona",
        "contraseña incorrecta siempre", "necesito entrar y no me deja",
        "¿cómo recupero mi contraseña?", "pasos para resetear contraseña",
        "donde pido una contraseña nueva", "se me olvidó como entrar",
        "ayúdame a recuperar mi acceso", "no me acuerdo de mi pass",
        "quiero restablecer mi forma de entrar", "el login me da error de contraseña",
        "no puedo entrar a mis consultas por la contraseña", "perdí mis datos de acceso",
        "recuperar pass", "olvido contraseña", "pass perdida", "sin contraseña",
        "cuenta perdida", "entrar salud lince ayuda", "no login", "reset pass",
        "ayuda login", "contraseña olvidada"
    ],

    "cambiar_password": [
        "quiero cambiar mi contraseña", "cambiar contraseña actual", 
        "actualizar mi contraseña", "modificar contraseña", 
        "poner una nueva contraseña", "quiero otra contraseña",
        "cambiarla por seguridad", "renovar mi contraseña",
        "asignar nueva contraseña", "editar mi contraseña de acceso",
        "mi contraseña es insegura quiero cambiarla", "mejorar mi seguridad de contraseña",
        "cambio de contraseña preventivo", "quiero proteger mejor mi cuenta con otra contraseña",
        "hacer mi contraseña más fuerte", "actualización de datos de acceso",
        "por seguridad quiero cambiar mi contraseña", "cambiar mi pass por uno nuevo",
        "¿dónde se cambia la contraseña?", "¿cómo cambio mi contraseña en mi perfil?",
        "pasos para poner otra contraseña", "instrucciones para actualizar contraseña",
        "quiero modificar mi acceso desde el perfil", "donde esta el boton de cambiar contraseña",
        "ayuda para editar mi contraseña", "guíame para cambiar mi contraseña",
        "ya no quiero esta contraseña", "quiero quitar mi contraseña vieja",
        "poner una contraseña que me guste más", "actualizar mis credenciales de entrada",
        "cambiar mi contraseña de salud lince", "ajustes de contraseña",
        "quiero cambiar el modo de entrar", "configurar nueva contraseña",
        "deseo actualizar mi información de acceso", "cambiar contraseña de mi cuenta",
        "cambio contraseña", "update contraseña", "nueva contraseña",
        "editar contraseña", "modificar pass", "cambiar pass", 
        "otra contraseña", "contraseña nueva por favor", "actualizar password",
        "ajustar contraseña", "cambiar entrada", "reset contraseña voluntario",
        "contraseña diferente", "cambiar mi secret"
    ],

    "ver_historial": [
        "quiero ver mi historial médico", "mostrar mi expediente", 
        "ver mis antecedentes", "consultar mi historial de salud",
        "ver mi expediente clínico", "quiero checar mi historial",
        "muéstrame mis datos médicos", "ver el registro de mi salud",
        "acceder a mi información médica", "revisar mi historial clínico",
        "¿cómo ha estado mi salud?", "ver mi progreso médico",
        "quiero ver lo que el doctor anotó", "mostrar mis diagnósticos",
        "ver mi resumen de salud", "quiero ver cómo voy en mi tratamiento",
        "historial de enfermedades", "ver mis alergias y antecedentes",
        "consultar mi estado clínico", "ver mi ficha médica",
        "quiero ver lo mío", "enséñame mis datos", "¿dónde están mis papeles médicos?",
        "ver mi información de paciente", "quiero ver mis resultados",
        "¿qué dice mi historial?", "quiero checar mi salud lince",
        "ver lo que tengo en el sistema", "muéstrame mi salud", "ver mi historial",
        "¿dónde está mi historial médico?", "quiero entrar a mi expediente",
        "¿cómo veo mi historial?", "pasos para ver mi historial de salud",
        "botón para ver historial", "dónde consulto mi información clínica",
        "quiero abrir mi historial", "acceso a mis datos de salud lince",
        "mi historial", "expediente médico", "antecedentes clínicos",
        "ver historial", "checar expediente", "datos de salud",
        "historial clínico", "mi expediente lince", "ver ficha",
        "info médica", "resumen médico", "historial lince"
    ],

    "ver_consultas": [
        "ver las consultas a las que he ido", "mostrar mis consultas pasadas", 
        "ver mi historial de visitas al médico", "consultas realizadas",
        "quiero ver a qué consultas he asistido", "lista de mis consultas tomadas",
        "ver el registro de mis consultas", "checar mis asistencias médicas",
        "ver consultas previas", "mostrar las consultas que ya tuve",
        "¿a qué consultas he asistido?", "ver mis asistencias a consulta",
        "quiero ver mis visitas médicas", "mostrar el registro de asistencia",
        "ver consultas anteriores", "checar mis citas pasadas",
        "¿cuántas veces he venido a consulta?", "ver mis entradas a consulta",
        "registro de mis citas atendidas", "ver mis consultas ya hechas",
        "quiero ver mis consultas", "¿dónde veo mis consultas pasadas?",
        "mostrar mis datos de consultas", "ver las veces que he consultado",
        "¿qué consultas tengo registradas?", "ver mi lista de consultas",
        "quiero checar mis consultas en salud lince", "ver el historial de mis citas",
        "mostrar información de mis consultas", "revisar mis asistencias",
        "¿dónde aparecen mis consultas?", "quiero entrar a ver mis consultas",
        "¿cómo consulto mis visitas pasadas?", "pasos para ver mis consultas asistidas",
        "ver tabla de consultas", "dónde checo mis consultas",
        "quiero abrir mi registro de consultas", "acceso a mis asistencias médicas",
        "mis consultas", "consultas asistidas", "visitas realizadas",
        "ver consultas", "checar consultas", "historial de visitas",
        "citas pasadas", "mis asistencias", "ver visitas",
        "registro médico de visitas", "consultas lince", "mis citas"
    ],

    "agregar_contacto": [
        "añadir contacto de emergencia", "registrar número de emergencia", 
        "poner a alguien para emergencias", "quiero agregar un contacto de auxilio",
        "dar de alta contacto de seguridad", "quien avisar en caso de emergencia",
        "configurar mi contacto de urgencia", "poner un teléfono para emergencias",
        "agregar a alguien por si me pasa algo", "registrar mi número de confianza",
        "agregar a mi mamá como contacto", "añadir a un familiar", 
        "poner el número de mi padre", "quiero registrar a mi hermano para avisarle",
        "agregar a un amigo de confianza", "vincular contacto familiar",
        "poner los datos de mi tutor", "añadir el teléfono de mi pareja",
        "registrar a una persona responsable", "poner a un pariente de contacto",
        "¿cómo agrego un contacto?", "¿dónde pongo los números de emergencia?",
        "pasos para añadir contacto en mi perfil", "quiero editar mis contactos",
        "donde se registran los contactos de confianza", "quiero subir un nuevo contacto",
        "actualizar mis contactos de emergencia", "cambiar mi contacto de ayuda",
        "quiero tener a alguien registrado para ayuda", "ayúdame a poner un contacto",
        "¿dónde se guardan los teléfonos de emergencia?", "quiero añadir a mi contacto",
        "meter un número nuevo al sistema", "registrar datos de un familiar",
        "guardar contacto de auxilio", "poner información de contacto",
        "quiero que el sistema tenga el número de mi casa", "añadir dato de confianza",
        "nuevo contacto", "contacto emergencia", "añadir teléfono",
        "registrar contacto", "número confianza", "info emergencia",
        "contacto auxilio", "poner contacto", "subir contacto",
        "contacto lince", "ayuda emergencia", "vincular familiar"
    ],

    "iniciar_sesion": [
        "quiero iniciar sesión", "entrar al sistema", "acceder a mi cuenta", 
        "ingresar a salud lince", "loguearme", "quiero entrar",
        "comenzar sesión", "abrir mi cuenta", "validar mi acceso",
        "identificarme en el sistema", "entrar con mi usuario",
        "entrar con mi matrícula", "ingresar mi número de trabajador", 
        "acceder con mis datos de alumno", "entrar como empleado",
        "poner mi matrícula para entrar", "usar mi número de trabajador para acceder",
        "¿dónde pongo mi matrícula?", "ingresar credenciales de alumno",
        "identificarme con mi número de trabajador", "acceso por matrícula",
        "¿cómo inicio sesión?", "¿dónde se entra?", "ayúdame a ingresar",
        "no sé cómo entrar a mi cuenta", "pasos para iniciar sesión",
        "¿dónde está el login?", "quiero poner mi matrícula y contraseña",
        "guíame para entrar al sistema", "no encuentro donde iniciar sesión",    "poner mi contraseña para entrar", "ingresar con contraseña",
        "quiero validar mi contraseña", "poner mis datos de acceso",
        "usar mi contraseña institucional para entrar", "entrar con mi pass",
        "escribir mi contraseña en el login", "acceder con mi contraseña",
        "entrar", "ingresar", "acceder", "login", "log in", "go",
        "iniciar", "identificarme", "mi cuenta", "entrar ya",
        "acceso alumno", "acceso trabajador", "login salud lince",
        "entrar lince", "puerta de acceso", "iniciar portal"
    ],

    "despedida": [
        "adiós", "bye", "chao", "nos vemos", "hasta luego", "hasta pronto", "ahí nos vemos",
        "me retiro", "ya me voy", "sale vale", "sale pues", "sale bye", "bye bye",
        "gracias", "muchas gracias", "mil gracias", "te lo agradezco", "gracias por la ayuda",
        "gracias lincybot", "gracias lince", "muy amable", "gracias por todo", "ok gracias",
        "todo bien gracias", "era todo gracias", "perfecto gracias", "entendido gracias",
        "es todo por hoy", "ya no necesito nada más", "he terminado", "nada más",
        "listo gracias", "ya quedó", "terminamos", "puedes descansar", "fin de la charla",
        "que tengas buen día", "cuídate", "luego te busco", "nos vemos después",
        "que estés bien", "hasta la próxima", "lindo día", "bonita tarde", "buenas noches adiós",
        "gracias por tu tiempo", "fuiste muy útil", "excelente servicio", "hablamos luego"
    ],

    "salir": [
        "cerrar sesión", "salir del sistema", "hacer logout", "desconectarme",
        "quiero salir", "finalizar sesión", "quitar mi cuenta", "desloguear",
        "terminar sesión", "cerrar mi acceso", "salida segura",
        "quiero cerrar mi sesión ahora", "cerrar cuenta por seguridad",
        "no dejar mi sesión abierta", "quiero salir de mi perfil",
        "desvincular mi sesión", "cerrar el portal", "bloquear sesión al salir",
        "¿cómo cierro sesión?", "¿dónde está el botón de salir?", "quiero salirme",
        "pasos para cerrar sesión", "donde se hace el logout", "quiero desloguearme",
        "ayúdame a salir de mi cuenta", "instrucciones para finalizar sesión",
        "salir de salud lince", "cerrar sesión lince", "terminar sesión de alumno",
        "cerrar mi número de trabajador", "quitar mi matrícula del sistema",
        "salir del expediente", "cerrar portal salud lince",
        "exit", "logout", "log out", "quit", "fuera", "cerrar", "off",
        "desconectar", "terminar", "cerrado", "botón salir", "desconexión",
        "ya no quiero estar conectado", "cerrar sesión por favor"
    ]
}